#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: ./create <filename>"
    echo "Example: ./create A"
    exit 1
fi

FILENAME="$1"

# Add .cc extension if not provided
if [[ ! "$FILENAME" =~ \.cc$ ]]; then
    FILENAME="${FILENAME}.cc"
fi

if [ -f "$FILENAME" ]; then
    echo "File $FILENAME already exists!"
    exit 1
fi

cp template.cc "$FILENAME"
echo "Created $FILENAME from template"
